version: '3.8'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=app
      - DD_ENV=${ENVIRONMENT}
      - DATABASE_URL=postgresql://user:password@localhost:5432/student_management
    networks:
      - datadog-agent-monitoring
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.development
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - default

  test:
    build: .
    command: pytest tests/
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/student_management
    networks:
      - app-network
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - test

  db:
    image: postgres:15
    container_name: student_management_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'listen_addresses=*'

networks:
  datadog-agent-monitoring:
    external: true
  app-network:
    driver: bridge

volumes:
  postgres_data: